from pathlib import Path
import sys, json, traceback
import difflib

sys.path.insert(0, r"F:\AGENT TRAIL")

try:
    from vidar.agent import VidarAgent
    from vidar.tools import ToolRegistry, Action
except Exception as e:
    print("IMPORT_ERROR", e)
    raise

agent = VidarAgent()
mission = "Add logging to all CLI command handlers and update README with usage examples"

try:
    plan = agent._generate_codebase_action_plan(Path('.'), mission)
    if plan is None:
        print("No plan generated by model.")
        sys.exit(0)

    if isinstance(plan, str):
        try:
            parsed = json.loads(plan)
        except Exception:
            print("Model returned text (non-JSON):")
            print(plan)
            parsed = None
    else:
        parsed = plan

    if not parsed:
        print("No actionable items parsed.")
        sys.exit(0)

    registry = ToolRegistry()
    try:
        actions = registry.parse_actions(parsed)
    except Exception as e:
        print("Failed to parse actions:", e)
        actions = []

    if not actions:
        print("No actions to preview.")
        sys.exit(0)

    print("Preview of planned actions (no changes will be made):\n")
    for a in actions:
        print(f"Action: {a.type} Path: {a.path} Cmd: {a.cmd}")
        if a.type in ("create", "write"):
            target = Path(a.path or "")
            new_content = a.content or ""  # If model didn't provide content, it's blank
            if target.exists() and target.is_file():
                old = target.read_text(encoding='utf-8').splitlines(keepends=True)
            else:
                old = []
            new = new_content.splitlines(keepends=True)
            diff = list(difflib.unified_diff(old, new, fromfile=f"a/{target}", tofile=f"b/{target}"))
            if diff:
                print("".join(diff))
            else:
                if not old and new:
                    print(f"Would create file {target} with {len(new)} lines.")
                elif old and not new:
                    print(f"Would truncate/empty file {target}.")
                else:
                    print(f"No content changes detected for {target}.")
        elif a.type == "delete":
            target = Path(a.path or "")
            exists = target.exists()
            print(f"Would delete {target} (exists={exists}, force={a.force})")
        elif a.type == "list":
            print(f"Would list directory: {a.path or '.'}")
        elif a.type == "exec":
            print(f"Would execute command: {a.cmd} (engine={a.engine})")
        else:
            print(f"Unsupported action type in preview: {a.type}")
        print("---")

except Exception as e:
    print("ERROR", e)
    traceback.print_exc()
