from pathlib import Path
import sys, json, traceback

sys.path.insert(0, r"F:\AGENT TRAIL")

try:
    from vidar.agent import VidarAgent
    from vidar.tools import ToolRegistry
except Exception as e:
    print("IMPORT_ERROR", e)
    raise

agent = VidarAgent()
mission = "Add logging to all CLI command handlers and update README with usage examples"

try:
    # Attempt to generate a codebase action plan using the agent's generator
    plan = agent._generate_codebase_action_plan(Path('.'), mission)
    if plan is None:
        print("No plan generated by model.")
    else:
        # If plan is a JSON string, attempt to parse
        if isinstance(plan, str):
            try:
                parsed = json.loads(plan)
            except Exception:
                # If it's just text, print and exit
                print("Model returned text (non-JSON):")
                print(plan)
                parsed = None
        else:
            parsed = plan

        if parsed:
            # Use ToolRegistry.parse_actions to normalize
            registry = ToolRegistry()
            try:
                actions = registry.parse_actions(parsed)
            except Exception as e:
                print("Failed to parse actions:", e)
                actions = []

            if not actions:
                print("No actionable items parsed.")
            else:
                print("Simulated actions (dry-run):")
                for a in actions:
                    print(f"- {a.type}: path={a.path} cmd={a.cmd} mkdir={a.mkdir} parents={a.parents} force={a.force}")

except Exception as e:
    print("ERROR", e)
    traceback.print_exc()
